import { BrainCircuit } from 'lucide-react'
import type { RiskFactor } from '../../types/api'

interface ExplainableAIPanelProps {
  explanation: string | null
  riskFactors: RiskFactor[]
  confidence: number
}

const FACTOR_COLORS: Record<string, string> = {
  Humidity: 'bg-sky-400',
  Temperature: 'bg-rose-400',
  Pressure: 'bg-violet-400',
  CAPE: 'bg-amber-400',
  'Lifted Index': 'bg-orange-400',
  'Wind Shear': 'bg-cyan-400',
  Precipitation: 'bg-blue-400',
  Latitude: 'bg-emerald-400',
}

function getFactorColor(name: string): string {
  return FACTOR_COLORS[name] ?? 'bg-slate-400'
}

export default function ExplainableAIPanel({
  explanation,
  riskFactors,
  confidence,
}: ExplainableAIPanelProps) {
  if (!explanation && riskFactors.length === 0) {
    return null
  }

  const maxContribution = Math.max(...riskFactors.map((f) => f.contribution), 0.01)

  return (
    <section className="rounded-2xl border border-violet-800/40 bg-gradient-to-br from-violet-950/30 via-slate-900 to-slate-900 p-5">
      <div className="flex items-center gap-2 mb-4">
        <BrainCircuit className="h-5 w-5 text-violet-400" aria-hidden="true" />
        <h3 className="text-sm font-semibold uppercase tracking-wider text-violet-300">
          Why This Risk?
        </h3>
        <span className="ml-auto rounded-full border border-violet-700 bg-violet-900/40 px-2 py-0.5 text-xs text-violet-300">
          Explainable AI
        </span>
      </div>

      {explanation && (
        <p className="mb-4 text-sm leading-relaxed text-slate-300">{explanation}</p>
      )}

      <div className="mb-4 rounded-xl border border-slate-800 bg-slate-950/50 p-3">
        <div className="flex items-center justify-between mb-1">
          <span className="text-xs text-slate-500">Model Confidence</span>
          <span className="text-sm font-mono font-semibold text-violet-300">
            {Math.round(confidence * 100)}%
          </span>
        </div>
        <div className="h-2 w-full overflow-hidden rounded-full bg-slate-800">
          <div
            className="h-full rounded-full bg-gradient-to-r from-violet-500 to-violet-400 transition-all"
            style={{ width: `${confidence * 100}%` }}
          />
        </div>
      </div>

      {riskFactors.length > 0 && (
        <div>
          <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-500 mb-3">
            Contributing Factors
          </h4>
          <div className="space-y-2">
            {riskFactors.map((factor) => {
              const barWidth = (factor.contribution / maxContribution) * 100
              return (
                <div
                  key={factor.name}
                  className="rounded-lg border border-slate-800 bg-slate-950/30 p-3"
                >
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2">
                      <span
                        className={`h-2 w-2 rounded-full ${getFactorColor(factor.name)}`}
                      />
                      <span className="text-sm font-medium text-slate-200">
                        {factor.name}
                      </span>
                    </div>
                    <span className="text-xs font-mono text-slate-400">
                      +{Math.round(factor.contribution * 100)}%
                    </span>
                  </div>
                  <div className="h-1.5 w-full overflow-hidden rounded-full bg-slate-800 mb-1">
                    <div
                      className={`h-full rounded-full ${getFactorColor(factor.name)} transition-all`}
                      style={{ width: `${barWidth}%`, opacity: 0.8 }}
                    />
                  </div>
                  <p className="text-xs text-slate-500">{factor.description}</p>
                </div>
              )
            })}
          </div>
        </div>
      )}

      <p className="mt-4 text-xs text-slate-600 italic">
        This analysis is generated by the ThunderCast rule-based risk engine for
        demonstration purposes. It is not a trained ML model and has not been
        evaluated against real data.
      </p>
    </section>
  )
}
